declare const styles: {
  readonly "action-btn": string;
  readonly "action-buttons": string;
  readonly "active": string;
  readonly "add-event-modal": string;
  readonly "buy": string;
  readonly "cancel-btn": string;
  readonly "checkbox-label": string;
  readonly "close-btn": string;
  readonly "content-fields": string;
  readonly "content-toggle": string;
  readonly "current-price-ref": string;
  readonly "error": string;
  readonly "error-text": string;
  readonly "event-form": string;
  readonly "event-type-btn": string;
  readonly "event-type-buttons": string;
  readonly "flex-grow": string;
  readonly "form-group": string;
  readonly "form-group-label": string;
  readonly "form-row": string;
  readonly "icon": string;
  readonly "injury": string;
  readonly "int": string;
  readonly "modal-actions": string;
  readonly "modal-header": string;
  readonly "modal-overlay": string;
  readonly "price-input-row": string;
  readonly "sell": string;
  readonly "stats": string;
  readonly "sub-type-btn": string;
  readonly "sub-type-buttons": string;
  readonly "submit-btn": string;
  readonly "suggest-btn": string;
  readonly "td": string;
};
export = styles;

